// Auto-generated stub types for Steamworks.NET
namespace Steamworks;

public class SteamAppList { }
public class SteamApps { }
public class SteamClient { }
public class SteamFriends { }
public class SteamGameServer { }
public class SteamGameServerClient { }
public class SteamGameServerHTTP { }
public class SteamGameServerInventory { }
public class SteamGameServerNetworking { }
public class SteamGameServerNetworkingSockets { }
public class SteamGameServerNetworkingUtils { }
public class SteamGameServerStats { }
public class SteamGameServerUGC { }
public class SteamGameServerUtils { }
public class SteamHTMLSurface { }
public class SteamHTTP { }
public class SteamInput { }
public class SteamInventory { }
public class SteamMatchmaking { }
public class SteamMatchmakingServers { }
public class SteamGameSearch { }
public class SteamParties { }
public class SteamMusic { }
public class SteamMusicRemote { }
public class SteamNetworking { }
public class SteamNetworkingSockets { }
public class SteamNetworkingUtils { }
public class SteamParentalSettings { }
public class SteamRemotePlay { }
public class SteamRemoteStorage { }
public class SteamScreenshots { }
public class SteamUGC { }
public class SteamUser { }
public class SteamUserStats { }
public class SteamUtils { }
public class SteamVideo { }
public class SteamAppInstalled_t { }
public class SteamAppUninstalled_t { }
public class DlcInstalled_t { }
public class RegisterActivationCodeResponse_t { }
public class NewUrlLaunchParameters_t { }
public class AppProofOfPurchaseKeyResponse_t { }
public class FileDetailsResult_t { }
public class TimedTrialStatus_t { }
public class PersonaStateChange_t { }
public class GameOverlayActivated_t { }
public class GameServerChangeRequested_t { }
public class GameLobbyJoinRequested_t { }
public class AvatarImageLoaded_t { }
public class ClanOfficerListResponse_t { }
public class FriendRichPresenceUpdate_t { }
public class GameRichPresenceJoinRequested_t { }
public class GameConnectedClanChatMsg_t { }
public class GameConnectedChatJoin_t { }
public class GameConnectedChatLeave_t { }
public class DownloadClanActivityCountsResult_t { }
public class JoinClanChatRoomCompletionResult_t { }
public class GameConnectedFriendChatMsg_t { }
public class FriendsGetFollowerCount_t { }
public class FriendsIsFollowing_t { }
public class FriendsEnumerateFollowingList_t { }
public class SetPersonaNameResponse_t { }
public class UnreadChatMessagesChanged_t { }
public class OverlayBrowserProtocolNavigation_t { }
public class GCMessageAvailable_t { }
public class GCMessageFailed_t { }
public class GSClientApprove_t { }
public class GSClientDeny_t { }
public class GSClientKick_t { }
public class GSClientAchievementStatus_t { }
public class GSPolicyResponse_t { }
public class GSGameplayStats_t { }
public class GSClientGroupStatus_t { }
public class GSReputation_t { }
public class AssociateWithClanResult_t { }
public class ComputeNewPlayerCompatibilityResult_t { }
public class GSStatsReceived_t { }
public class GSStatsStored_t { }
public class GSStatsUnloaded_t { }
public class HTML_BrowserReady_t { }
public class HTML_NeedsPaint_t { }
public class HTML_StartRequest_t { }
public class HTML_CloseBrowser_t { }
public class HTML_URLChanged_t { }
public class HTML_FinishedRequest_t { }
public class HTML_OpenLinkInNewTab_t { }
public class HTML_ChangedTitle_t { }
public class HTML_SearchResults_t { }
public class HTML_CanGoBackAndForward_t { }
public class HTML_HorizontalScroll_t { }
public class HTML_VerticalScroll_t { }
public class HTML_LinkAtPosition_t { }
public class HTML_JSAlert_t { }
public class HTML_JSConfirm_t { }
public class HTML_FileOpenDialog_t { }
public class HTML_NewWindow_t { }
public class HTML_SetCursor_t { }
public class HTML_StatusText_t { }
public class HTML_ShowToolTip_t { }
public class HTML_UpdateToolTip_t { }
public class HTML_HideToolTip_t { }
public class HTML_BrowserRestarted_t { }
public class HTTPRequestCompleted_t { }
public class HTTPRequestHeadersReceived_t { }
public class HTTPRequestDataReceived_t { }
public class SteamInputDeviceConnected_t { }
public class SteamInputDeviceDisconnected_t { }
public class SteamInputConfigurationLoaded_t { }
public class SteamInventoryResultReady_t { }
public class SteamInventoryFullUpdate_t { }
public class SteamInventoryDefinitionUpdate_t { }
public class SteamInventoryEligiblePromoItemDefIDs_t { }
public class SteamInventoryStartPurchaseResult_t { }
public class SteamInventoryRequestPricesResult_t { }
public class FavoritesListChanged_t { }
public class LobbyInvite_t { }
public class LobbyEnter_t { }
public class LobbyDataUpdate_t { }
public class LobbyChatUpdate_t { }
public class LobbyChatMsg_t { }
public class LobbyGameCreated_t { }
public class LobbyMatchList_t { }
public class LobbyKicked_t { }
public class LobbyCreated_t { }
public class FavoritesListAccountsUpdated_t { }
public class SearchForGameProgressCallback_t { }
public class SearchForGameResultCallback_t { }
public class RequestPlayersForGameProgressCallback_t { }
public class RequestPlayersForGameResultCallback_t { }
public class RequestPlayersForGameFinalResultCallback_t { }
public class SubmitPlayerResultResultCallback_t { }
public class EndGameResultCallback_t { }
public class JoinPartyCallback_t { }
public class CreateBeaconCallback_t { }
public class ReservationNotificationCallback_t { }
public class ChangeNumOpenSlotsCallback_t { }
public class AvailableBeaconLocationsUpdated_t { }
public class ActiveBeaconsUpdated_t { }
public class PlaybackStatusHasChanged_t { }
public class VolumeHasChanged_t { }
public class MusicPlayerRemoteWillActivate_t { }
public class MusicPlayerRemoteWillDeactivate_t { }
public class MusicPlayerRemoteToFront_t { }
public class MusicPlayerWillQuit_t { }
public class MusicPlayerWantsPlay_t { }
public class MusicPlayerWantsPause_t { }
public class MusicPlayerWantsPlayPrevious_t { }
public class MusicPlayerWantsPlayNext_t { }
public class MusicPlayerWantsShuffled_t { }
public class MusicPlayerWantsLooped_t { }
public class MusicPlayerWantsVolume_t { }
public class MusicPlayerSelectsQueueEntry_t { }
public class MusicPlayerSelectsPlaylistEntry_t { }
public class MusicPlayerWantsPlayingRepeatStatus_t { }
public class P2PSessionRequest_t { }
public class P2PSessionConnectFail_t { }
public class SocketStatusCallback_t { }
public class SteamNetworkingMessagesSessionRequest_t { }
public class SteamNetworkingMessagesSessionFailed_t { }
public class SteamNetConnectionStatusChangedCallback_t { }
public class SteamNetAuthenticationStatus_t { }
public class SteamRelayNetworkStatus_t { }
public class SteamParentalSettingsChanged_t { }
public class SteamRemotePlaySessionConnected_t { }
public class SteamRemotePlaySessionDisconnected_t { }
public class RemoteStorageFileShareResult_t { }
public class RemoteStoragePublishFileResult_t { }
public class RemoteStorageDeletePublishedFileResult_t { }
public class RemoteStorageEnumerateUserPublishedFilesResult_t { }
public class RemoteStorageSubscribePublishedFileResult_t { }
public class RemoteStorageEnumerateUserSubscribedFilesResult_t { }
public class RemoteStorageUnsubscribePublishedFileResult_t { }
public class RemoteStorageUpdatePublishedFileResult_t { }
public class RemoteStorageDownloadUGCResult_t { }
public class RemoteStorageGetPublishedFileDetailsResult_t { }
public class RemoteStorageEnumerateWorkshopFilesResult_t { }
public class RemoteStorageGetPublishedItemVoteDetailsResult_t { }
public class RemoteStoragePublishedFileSubscribed_t { }
public class RemoteStoragePublishedFileUnsubscribed_t { }
public class RemoteStoragePublishedFileDeleted_t { }
public class RemoteStorageUpdateUserPublishedItemVoteResult_t { }
public class RemoteStorageUserVoteDetails_t { }
public class RemoteStorageEnumerateUserSharedWorkshopFilesResult_t { }
public class RemoteStorageSetUserPublishedFileActionResult_t { }
public class RemoteStorageEnumeratePublishedFilesByUserActionResult_t { }
public class RemoteStoragePublishFileProgress_t { }
public class RemoteStoragePublishedFileUpdated_t { }
public class RemoteStorageFileWriteAsyncComplete_t { }
public class RemoteStorageFileReadAsyncComplete_t { }
public class RemoteStorageLocalFileChange_t { }
public class ScreenshotReady_t { }
public class ScreenshotRequested_t { }
public class SteamUGCQueryCompleted_t { }
public class SteamUGCRequestUGCDetailsResult_t { }
public class CreateItemResult_t { }
public class SubmitItemUpdateResult_t { }
public class ItemInstalled_t { }
public class DownloadItemResult_t { }
public class UserFavoriteItemsListChanged_t { }
public class SetUserItemVoteResult_t { }
public class GetUserItemVoteResult_t { }
public class StartPlaytimeTrackingResult_t { }
public class StopPlaytimeTrackingResult_t { }
public class AddUGCDependencyResult_t { }
public class RemoveUGCDependencyResult_t { }
public class AddAppDependencyResult_t { }
public class RemoveAppDependencyResult_t { }
public class GetAppDependenciesResult_t { }
public class DeleteItemResult_t { }
public class UserSubscribedItemsListChanged_t { }
public class WorkshopEULAStatus_t { }
public class SteamServersConnected_t { }
public class SteamServerConnectFailure_t { }
public class SteamServersDisconnected_t { }
public class ClientGameServerDeny_t { }
public class IPCFailure_t { }
public class LicensesUpdated_t { }
public class ValidateAuthTicketResponse_t { }
public class MicroTxnAuthorizationResponse_t { }
public class EncryptedAppTicketResponse_t { }
public class GetAuthSessionTicketResponse_t { }
public class GameWebCallback_t { }
public class StoreAuthURLResponse_t { }
public class MarketEligibilityResponse_t { }
public class DurationControl_t { }
public class UserStatsReceived_t { }
public class UserStatsStored_t { }
public class UserAchievementStored_t { }
public class LeaderboardFindResult_t { }
public class LeaderboardScoresDownloaded_t { }
public class LeaderboardScoreUploaded_t { }
public class NumberOfCurrentPlayers_t { }
public class UserStatsUnloaded_t { }
public class UserAchievementIconFetched_t { }
public class GlobalAchievementPercentagesReady_t { }
public class LeaderboardUGCSet_t { }
public class GlobalStatsReceived_t { }
public class IPCountry_t { }
public class LowBatteryPower_t { }
public class SteamAPICallCompleted_t { }
public class SteamShutdown_t { }
public class CheckFileSignature_t { }
public class GamepadTextInputDismissed_t { }
public class AppResumingFromSuspend_t { }
public class FloatingGamepadTextInputDismissed_t { }
public class GetVideoURLResult_t { }
public class GetOPFSettingsResult_t { }
public class Constants { }
public enum ERegisterActivationCodeResult { }
public enum EFriendRelationship { }
public enum EPersonaState { }
public enum EFriendFlags { }
public enum EUserRestriction { }
public enum EOverlayToStoreFlag { }
public enum EActivateGameOverlayToWebPageMode { }
public enum EPersonaChange { }
public enum EGCResults { }
public enum EHTMLMouseButton { }
public enum EMouseCursor { }
public enum EHTMLKeyModifiers { }
public enum EInputSourceMode { }
public enum EInputActionOrigin { }
public enum EXboxOrigin { }
public enum ESteamControllerPad { }
public enum EControllerHapticLocation { }
public enum EControllerHapticType { }
public enum ESteamInputType { }
public enum ESteamInputConfigurationEnableType { }
public enum ESteamInputLEDFlag { }
public enum ESteamInputGlyphSize { }
public enum ESteamInputActionEventType { }
public enum ESteamItemFlags { }
public enum ELobbyType { }
public enum ELobbyComparison { }
public enum ELobbyDistanceFilter { }
public enum EChatMemberStateChange { }
public enum ESteamPartyBeaconLocationType { }
public enum ESteamPartyBeaconLocationData { }
public enum PlayerAcceptState_t { }
public enum AudioPlayback_Status { }
public enum EP2PSessionError { }
public enum EP2PSend { }
public enum ESNetSocketState { }
public enum ESNetSocketConnectionType { }
public enum EParentalFeature { }
public enum ESteamDeviceFormFactor { }
public enum ERemoteStoragePlatform { }
public enum ERemoteStoragePublishedFileVisibility { }
public enum EWorkshopFileType { }
public enum EWorkshopVote { }
public enum EWorkshopFileAction { }
public enum EWorkshopEnumerationType { }
public enum EWorkshopVideoProvider { }
public enum EUGCReadAction { }
public enum ERemoteStorageLocalFileChange { }
public enum ERemoteStorageFilePathType { }
public enum EVRScreenshotType { }
public enum EUGCMatchingUGCType { }
public enum EUserUGCList { }
public enum EUserUGCListSortOrder { }
public enum EUGCQuery { }
public enum EItemUpdateStatus { }
public enum EItemState { }
public enum EItemStatistic { }
public enum EItemPreviewType { }
public enum EFailureType { }
public enum ELeaderboardDataRequest { }
public enum ELeaderboardSortMethod { }
public enum ELeaderboardDisplayType { }
public enum ELeaderboardUploadScoreMethod { }
public enum ESteamAPICallFailure { }
public enum EGamepadTextInputMode { }
public enum EGamepadTextInputLineMode { }
public enum EFloatingGamepadTextInputMode { }
public enum ETextFilteringContext { }
public enum ECheckFileSignature { }
public enum EMatchMakingServerResponse { }
public enum EServerMode { }
public enum EResult { }
public enum EVoiceResult { }
public enum EDenyReason { }
public enum EBeginAuthSessionResult { }
public enum EAuthSessionResponse { }
public enum EUserHasLicenseForAppResult { }
public enum EAccountType { }
public enum EChatEntryType { }
public enum EChatRoomEnterResponse { }
public enum EChatSteamIDInstanceFlags { }
public enum ENotificationPosition { }
public enum EBroadcastUploadResult { }
public enum EMarketNotAllowedReasonFlags { }
public enum EDurationControlProgress { }
public enum EDurationControlNotification { }
public enum EDurationControlOnlineState { }
public enum EGameSearchErrorCode_t { }
public enum EPlayerResult_t { }
public enum ESteamIPv6ConnectivityProtocol { }
public enum ESteamIPv6ConnectivityState { }
public enum EHTTPMethod { }
public enum EHTTPStatusCode { }
public enum ESteamNetworkingAvailability { }
public enum ESteamNetworkingIdentityType { }
public enum ESteamNetworkingConnectionState { }
public enum ESteamNetConnectionEnd { }
public enum ESteamNetworkingConfigScope { }
public enum ESteamNetworkingConfigDataType { }
public enum ESteamNetworkingConfigValue { }
public enum ESteamNetworkingGetConfigValueResult { }
public enum ESteamNetworkingSocketsDebugOutputType { }
public enum ESteamIPType { }
public enum EUniverse { }
public class FriendGameInfo_t { }
public class InputAnalogActionData_t { }
public class InputDigitalActionData_t { }
public class InputMotionData_t { }
public class SteamItemDetails_t { }
public class SteamPartyBeaconLocation_t { }
public class P2PSessionState_t { }
public class SteamParamStringArray_t { }
public class SteamUGCDetails_t { }
public class LeaderboardEntry_t { }
public class MatchMakingKeyValuePair_t { }
public class CallbackMsg_t { }
public class SteamNetConnectionInfo_t { }
public class SteamNetworkingQuickConnectionStatus { }
public class SteamNetworkPingLocation_t { }
public class gameserveritem_t { }
public class servernetadr_t { }
public class HSteamPipe { }
public class HSteamUser { }
public class SteamAPI_CheckCallbackRegistered_t { }
public class SteamAPIWarningMessageHook_t { }
public class CGameID { }
public class CSteamID { }
public class HAuthTicket { }
public class SteamDatagramHostedAddress { }
public class SteamDatagramRelayAuthTicket { }
public class FriendsGroupID_t { }
public class HHTMLBrowser { }
public class HTTPCookieContainerHandle { }
public class HTTPRequestHandle { }
public class InputActionSetHandle_t { }
public class InputAnalogActionHandle_t { }
public class InputDigitalActionHandle_t { }
public class InputHandle_t { }
public class SteamInputActionEvent_t { }
public class SteamInputActionEventCallbackPointer { }
public class SteamInventoryResult_t { }
public class SteamInventoryUpdateHandle_t { }
public class SteamItemDef_t { }
public class SteamItemInstanceID_t { }
public class HServerListRequest { }
public class HServerQuery { }
public class SNetListenSocket_t { }
public class SNetSocket_t { }
public class ISteamNetworkingConnectionSignaling { }
public class ISteamNetworkingSignalingRecvContext { }
public class FSteamNetworkingSocketsDebugOutput { }
public class HSteamListenSocket { }
public class HSteamNetConnection { }
public class HSteamNetPollGroup { }
public class SteamNetworkingConfigValue_t { }
public class SteamNetworkingErrMsg { }
public class SteamNetworkingIdentity { }
public class SteamNetworkingIPAddr { }
public class SteamNetworkingMessage_t { }
public class SteamNetworkingMicroseconds { }
public class SteamNetworkingPOPID { }
public class RemotePlaySessionID_t { }
public class PublishedFileId_t { }
public class PublishedFileUpdateHandle_t { }
public class UGCFileWriteStreamHandle_t { }
public class UGCHandle_t { }
public class ScreenshotHandle { }
public class AccountID_t { }
public class AppId_t { }
public class DepotId_t { }
public class PartyBeaconID_t { }
public class RTime32 { }
public class SteamAPICall_t { }
public class SteamIPAddress_t { }
public class UGCQueryHandle_t { }
public class UGCUpdateHandle_t { }
public class SteamLeaderboard_t { }
public class SteamLeaderboardEntries_t { }
public class CallbackDispatcher { }
public class Callback { }
public class Callback`1 { }
public class CallResult { }
public class CallResult`1 { }
public class InteropHelp { }
public class MMKVPMarshaller { }
public class DllCheck { }
public class ISteamMatchmakingServerListResponse { }
public class ISteamMatchmakingPingResponse { }
public class ISteamMatchmakingPlayersResponse { }
public class ISteamMatchmakingRulesResponse { }
public class Packsize { }
public class SteamAPI { }
public class GameServer { }
public class SteamEncryptedAppTicket { }
public class Version { }
