// Auto-generated stub types for GalaxyCSharp
namespace Galaxy.Api;

public enum AvatarType { }
public enum ChatMessageType { }
public enum ConnectionType { }
public class GalaxyID { }
public class GalaxyInstance { }
public class GalaxyTypeAwareListenerAccessToken { }
public class GalaxyTypeAwareListenerAchievementChange { }
public class GalaxyTypeAwareListenerAuth { }
public class GalaxyTypeAwareListenerChatRoomMessages { }
public class GalaxyTypeAwareListenerChatRoomMessageSend { }
public class GalaxyTypeAwareListenerChatRoomMessagesRetrieve { }
public class GalaxyTypeAwareListenerChatRoomWithUserRetrieve { }
public class GalaxyTypeAwareListenerConnectionClose { }
public class GalaxyTypeAwareListenerConnectionData { }
public class GalaxyTypeAwareListenerConnectionOpen { }
public class GalaxyTypeAwareListenerEncryptedAppTicket { }
public class GalaxyTypeAwareListenerFileShare { }
public class GalaxyTypeAwareListenerFriendAdd { }
public class GalaxyTypeAwareListenerFriendDelete { }
public class GalaxyTypeAwareListenerFriendInvitation { }
public class GalaxyTypeAwareListenerFriendInvitationListRetrieve { }
public class GalaxyTypeAwareListenerFriendInvitationRespondTo { }
public class GalaxyTypeAwareListenerFriendInvitationSend { }
public class GalaxyTypeAwareListenerFriendList { }
public class GalaxyTypeAwareListenerGameInvitationReceived { }
public class GalaxyTypeAwareListenerGameJoinRequested { }
public class GalaxyTypeAwareListenerGogServicesConnectionState { }
public class GalaxyTypeAwareListenerLeaderboardEntriesRetrieve { }
public class GalaxyTypeAwareListenerLeaderboardRetrieve { }
public class GalaxyTypeAwareListenerLeaderboardScoreUpdate { }
public class GalaxyTypeAwareListenerLeaderboardsRetrieve { }
public class GalaxyTypeAwareListenerLobbyCreated { }
public class GalaxyTypeAwareListenerLobbyData { }
public class GalaxyTypeAwareListenerLobbyDataRetrieve { }
public class GalaxyTypeAwareListenerLobbyDataUpdate { }
public class GalaxyTypeAwareListenerLobbyEntered { }
public class GalaxyTypeAwareListenerLobbyLeft { }
public class GalaxyTypeAwareListenerLobbyList { }
public class GalaxyTypeAwareListenerLobbyMemberDataUpdate { }
public class GalaxyTypeAwareListenerLobbyMemberState { }
public class GalaxyTypeAwareListenerLobbyMessage { }
public class GalaxyTypeAwareListenerLobbyOwnerChange { }
public class GalaxyTypeAwareListenerNatTypeDetection { }
public class GalaxyTypeAwareListenerNetworking { }
public class GalaxyTypeAwareListenerNotification { }
public class GalaxyTypeAwareListenerOperationalStateChange { }
public class GalaxyTypeAwareListenerOtherSessionStart { }
public class GalaxyTypeAwareListenerOverlayInitializationStateChange { }
public class GalaxyTypeAwareListenerOverlayVisibilityChange { }
public class GalaxyTypeAwareListenerPersonaDataChanged { }
public class GalaxyTypeAwareListenerRichPresence { }
public class GalaxyTypeAwareListenerRichPresenceChange { }
public class GalaxyTypeAwareListenerRichPresenceRetrieve { }
public class GalaxyTypeAwareListenerSendInvitation { }
public class GalaxyTypeAwareListenerSentFriendInvitationListRetrieve { }
public class GalaxyTypeAwareListenerSharedFileDownload { }
public class GalaxyTypeAwareListenerSpecificUserData { }
public class GalaxyTypeAwareListenerStatsAndAchievementsStore { }
public class GalaxyTypeAwareListenerTelemetryEventSend { }
public class GalaxyTypeAwareListenerUserData { }
public class GalaxyTypeAwareListenerUserFind { }
public class GalaxyTypeAwareListenerUserInformationRetrieve { }
public class GalaxyTypeAwareListenerUserStatsAndAchievementsRetrieve { }
public class GalaxyTypeAwareListenerUserTimePlayedRetrieve { }
public class GameServerGlobalAccessTokenListener { }
public class GameServerGlobalAuthListener { }
public class GameServerGlobalEncryptedAppTicketListener { }
public class GameServerGlobalGogServicesConnectionStateListener { }
public class GameServerGlobalLobbyCreatedListener { }
public class GameServerGlobalLobbyDataListener { }
public class GameServerGlobalLobbyDataRetrieveListener { }
public class GameServerGlobalLobbyDataUpdateListener { }
public class GameServerGlobalLobbyEnteredListener { }
public class GameServerGlobalLobbyLeftListener { }
public class GameServerGlobalLobbyMemberDataUpdateListener { }
public class GameServerGlobalLobbyMemberStateListener { }
public class GameServerGlobalLobbyMessageListener { }
public class GameServerGlobalNetworkingListener { }
public class GameServerGlobalOperationalStateChangeListener { }
public class GameServerGlobalRichPresenceRetrieveListener { }
public class GameServerGlobalSpecificUserDataListener { }
public class GameServerGlobalTelemetryEventSendListener { }
public class GameServerGlobalUserInformationRetrieveListener { }
public class GlobalAccessTokenListener { }
public class GlobalAchievementChangeListener { }
public class GlobalAuthListener { }
public class GlobalChatRoomMessageSendListener { }
public class GlobalChatRoomMessagesListener { }
public class GlobalChatRoomMessagesRetrieveListener { }
public class GlobalChatRoomWithUserRetrieveListener { }
public class GlobalConnectionCloseListener { }
public class GlobalConnectionDataListener { }
public class GlobalConnectionOpenListener { }
public class GlobalEncryptedAppTicketListener { }
public class GlobalFileShareListener { }
public class GlobalFriendAddListener { }
public class GlobalFriendDeleteListener { }
public class GlobalFriendInvitationListener { }
public class GlobalFriendInvitationListRetrieveListener { }
public class GlobalFriendInvitationRespondToListener { }
public class GlobalFriendInvitationSendListener { }
public class GlobalFriendListListener { }
public class GlobalGameInvitationReceivedListener { }
public class GlobalGameJoinRequestedListener { }
public class GlobalGogServicesConnectionStateListener { }
public class GlobalLeaderboardEntriesRetrieveListener { }
public class GlobalLeaderboardRetrieveListener { }
public class GlobalLeaderboardScoreUpdateListener { }
public class GlobalLeaderboardsRetrieveListener { }
public class GlobalLobbyCreatedListener { }
public class GlobalLobbyDataListener { }
public class GlobalLobbyDataRetrieveListener { }
public class GlobalLobbyDataUpdateListener { }
public class GlobalLobbyEnteredListener { }
public class GlobalLobbyLeftListener { }
public class GlobalLobbyListListener { }
public class GlobalLobbyMemberDataUpdateListener { }
public class GlobalLobbyMemberStateListener { }
public class GlobalLobbyMessageListener { }
public class GlobalLobbyOwnerChangeListener { }
public class GlobalNatTypeDetectionListener { }
public class GlobalNetworkingListener { }
public class GlobalNotificationListener { }
public class GlobalOperationalStateChangeListener { }
public class GlobalOtherSessionStartListener { }
public class GlobalOverlayInitializationStateChangeListener { }
public class GlobalOverlayVisibilityChangeListener { }
public class GlobalPersonaDataChangedListener { }
public class GlobalRichPresenceChangeListener { }
public class GlobalRichPresenceListener { }
public class GlobalRichPresenceRetrieveListener { }
public class GlobalSendInvitationListener { }
public class GlobalSentFriendInvitationListRetrieveListener { }
public class GlobalSharedFileDownloadListener { }
public class GlobalSpecificUserDataListener { }
public class GlobalStatsAndAchievementsStoreListener { }
public class GlobalTelemetryEventSendListener { }
public class GlobalUserDataListener { }
public class GlobalUserFindListener { }
public class GlobalUserInformationRetrieveListener { }
public class GlobalUserStatsAndAchievementsRetrieveListener { }
public class GlobalUserTimePlayedRetrieveListener { }
public enum GogServicesConnectionState { }
public class IAccessTokenListener { }
public class IAchievementChangeListener { }
public class IApps { }
public class IAuthListener { }
public class IChat { }
public class IChatRoomMessageSendListener { }
public class IChatRoomMessagesListener { }
public class IChatRoomMessagesRetrieveListener { }
public class IChatRoomWithUserRetrieveListener { }
public class IConnectionCloseListener { }
public class IConnectionDataListener { }
public class IConnectionOpenListener { }
public class ICustomNetworking { }
public class IEncryptedAppTicketListener { }
public class IError { }
public class IFileShareListener { }
public class IFriendAddListener { }
public class IFriendDeleteListener { }
public class IFriendInvitationListener { }
public class IFriendInvitationListRetrieveListener { }
public class IFriendInvitationRespondToListener { }
public class IFriendInvitationSendListener { }
public class IFriendListListener { }
public class IFriends { }
public class IGalaxyListener { }
public class IGameInvitationReceivedListener { }
public class IGameJoinRequestedListener { }
public class IGogServicesConnectionStateListener { }
public class IInvalidArgumentError { }
public class IInvalidStateError { }
public class ILeaderboardEntriesRetrieveListener { }
public class ILeaderboardRetrieveListener { }
public class ILeaderboardScoreUpdateListener { }
public class ILeaderboardsRetrieveListener { }
public class IListenerRegistrar { }
public class ILobbyCreatedListener { }
public class ILobbyDataListener { }
public class ILobbyDataRetrieveListener { }
public class ILobbyDataUpdateListener { }
public class ILobbyEnteredListener { }
public class ILobbyLeftListener { }
public class ILobbyListListener { }
public class ILobbyMemberDataUpdateListener { }
public class ILobbyMemberStateListener { }
public class ILobbyMessageListener { }
public class ILobbyOwnerChangeListener { }
public class ILogger { }
public class IMatchmaking { }
public class INatTypeDetectionListener { }
public class INetworking { }
public class INetworkingListener { }
public class InitParams { }
public class INotificationListener { }
public class IOperationalStateChangeListener { }
public class IOtherSessionStartListener { }
public class IOverlayInitializationStateChangeListener { }
public class IOverlayVisibilityChangeListener { }
public class IPersonaDataChangedListener { }
public class IRichPresenceChangeListener { }
public class IRichPresenceListener { }
public class IRichPresenceRetrieveListener { }
public class IRuntimeError { }
public class ISendInvitationListener { }
public class ISentFriendInvitationListRetrieveListener { }
public class ISharedFileDownloadListener { }
public class ISpecificUserDataListener { }
public class IStats { }
public class IStatsAndAchievementsStoreListener { }
public class IStorage { }
public class ITelemetry { }
public class ITelemetryEventSendListener { }
public class IUnauthorizedAccessError { }
public class IUser { }
public class IUserDataListener { }
public class IUserFindListener { }
public class IUserInformationRetrieveListener { }
public class IUserStatsAndAchievementsRetrieveListener { }
public class IUserTimePlayedRetrieveListener { }
public class IUtils { }
public enum LeaderboardDisplayType { }
public enum LeaderboardSortMethod { }
public enum ListenerType { }
public enum LobbyComparisonType { }
public enum LobbyCreateResult { }
public enum LobbyEnterResult { }
public enum LobbyListResult { }
public enum LobbyMemberStateChange { }
public enum LobbyTopologyType { }
public enum LobbyType { }
public class MonoPInvokeCallbackAttribute { }
public enum NatType { }
public enum OverlayState { }
public enum P2PSendType { }
public enum PersonaState { }
