#!/usr/bin/env bash
# Generates src/MonoGame.Framework.Facade/AssemblyInfo.cs by enumerating
# all public non-generic types in the KNI assemblies via reflection.
# Re-run after upgrading KNI to pick up newly-added types.
set -euo pipefail
export PATH="$HOME/.dotnet:$PATH"
export DOTNET_ROOT="$HOME/.dotnet"
cd "$(dirname "$0")/.."

if [ ! -d src/MonoGame.Framework.Facade ]; then
    echo "[!] src/MonoGame.Framework.Facade not found — run from project root" >&2
    exit 1
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

cat > "$TMP/Enumerator.csproj" <<'EOF'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Enumerator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="nkast.Xna.Framework" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Game" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Graphics" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Content" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Input" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Audio" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Media" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Devices" Version="4.2.9001" />
    <PackageReference Include="nkast.Xna.Framework.Storage" Version="4.2.9001" />
  </ItemGroup>
</Project>
EOF

mkdir -p "$TMP/Program"
cat > "$TMP/Program/Program.cs" <<'EOF'
using System;
using System.Linq;
using System.Reflection;

string[] kniAssemblies = new[] {
    "Xna.Framework",
    "Xna.Framework.Game",
    "Xna.Framework.Graphics",
    "Xna.Framework.Content",
    "Xna.Framework.Input",
    "Xna.Framework.Audio",
    "Xna.Framework.Media",
    "Xna.Framework.Devices",
    "Xna.Framework.Storage",
    "Xna.Framework.XR",
};

// Force-load all KNI assemblies explicitly by name.
foreach (var name in kniAssemblies)
{
    try { AppDomain.CurrentDomain.Load(new AssemblyName(name)); }
    catch (Exception ex) { Console.Error.WriteLine($"[!] Failed to preload {name}: {ex.Message}"); }
}
// Touch specific types to ensure assemblies are loaded (not just metadata):
try { _ = typeof(Microsoft.Xna.Framework.Vector2); } catch { }       // Xna.Framework
try { _ = typeof(Microsoft.Xna.Framework.Game); } catch { }          // Xna.Framework.Game
try { _ = typeof(Microsoft.Xna.Framework.Graphics.Texture2D); } catch { } // Xna.Framework.Graphics
try { _ = typeof(Microsoft.Xna.Framework.Content.ContentManager); } catch { } // Xna.Framework.Content
try { _ = typeof(Microsoft.Xna.Framework.Input.KeyboardState); } catch { } // Xna.Framework.Input

Console.WriteLine("// <auto-generated by scripts/generate-facade-types.sh />");
Console.WriteLine("// Forward every public non-generic type from the 5 KNI assemblies");
Console.WriteLine("// to satisfy SDV's MonoGame.Framework AssemblyRef.");
Console.WriteLine("//");
Console.WriteLine("// Regenerate after KNI upgrades with:");
Console.WriteLine("//   ./scripts/generate-facade-types.sh");
Console.WriteLine("using System.Reflection;");
Console.WriteLine("using System.Runtime.CompilerServices;");
Console.WriteLine("");
// SDV was compiled against MonoGame.Framework — real GOG SDV v1.6.15 uses
// v3.8.0.1641. The facade's AssemblyVersion should match to avoid any
// potential version resolution issues (though unsigned assemblies are
// generally not version-checked in practice — proven in Phase 2).
Console.WriteLine("[assembly: AssemblyVersion(\"3.8.0.1641\")]");
Console.WriteLine("[assembly: AssemblyFileVersion(\"3.8.0.1641\")]");
Console.WriteLine("");
Console.WriteLine("");

int total = 0;
foreach (var asmName in kniAssemblies)
{
    var asm = AppDomain.CurrentDomain.GetAssemblies()
        .FirstOrDefault(a => a.GetName().Name == asmName);
    if (asm == null)
    {
        Console.Error.WriteLine($"[!] Assembly not loaded: {asmName}");
        continue;
    }
    Type[] types;
    try { types = asm.GetTypes(); }
    catch (ReflectionTypeLoadException ex)
    {
        types = ex.Types.Where(t => t != null).ToArray()!;
        Console.Error.WriteLine($"[!] {asmName}: {ex.Types.Length - types.Length} types failed to load");
    }

    int asmCount = 0;
    foreach (var t in types.Where(t => t.IsPublic))
    {
        // Skip open generic types — TypeForwardedTo cannot forward open generics
        // (CLR restriction: forwarded types must be closed or non-generic).
        if (t.IsGenericTypeDefinition) continue;
        // Skip types with generic parameters (would also fail at forward time).
        if (t.ContainsGenericParameters) continue;
        // Skip types whose namespace is null (rare in KNI, but defensive).
        if (string.IsNullOrEmpty(t.Namespace)) continue;
        Console.WriteLine($"[assembly: TypeForwardedTo(typeof({t.FullName}))]");
        asmCount++;
        total++;
    }
    Console.Error.WriteLine($"[+] {asmName}: forwarded {asmCount} public types");
}
Console.Error.WriteLine($"[+] Total TypeForwardedTo attributes: {total}");
EOF

dotnet run --project "$TMP" > src/MonoGame.Framework.Facade/AssemblyInfo.cs
echo "[+] Wrote src/MonoGame.Framework.Facade/AssemblyInfo.cs"
wc -l src/MonoGame.Framework.Facade/AssemblyInfo.cs
